remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Mauricio Gonz√°lez-Forero's personal website]

google_analytics: [G-72ZC87Y726]
